// <auto-generated />
namespace Garage2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Slotbelongstogarage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Slotbelongstogarage));
        
        string IMigrationMetadata.Id
        {
            get { return "201611141022087_Slot belongs to garage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
